/*
 * sm121-kernels C API demo
 *
 * Build order (the header is generated by cbindgen, not checked in):
 *   make header                              # writes include/sm121_kernels.h via cbindgen
 *   cargo build --release --features c-api   # builds target/release/libsm121_kernels.so
 *   gcc -DSPARK_C_API -o c_api_demo examples/c_api_demo.c \
 *       -Iinclude \
 *       -Ltarget/release -lsm121_kernels \
 *       -lcuda -Wl,-rpath,target/release
 *
 * Run:
 *   ./c_api_demo
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <cuda.h>
#include "sm121_kernels.h"

#define CHECK_SPARK(call) do { \
    SparkStatus s = (call); \
    if (s != SPARK_STATUS_SUCCESS) { \
        fprintf(stderr, "spark error %d at %s:%d\n", s, __FILE__, __LINE__); \
        exit(1); \
    } \
} while (0)

#define CHECK_CUDA(call) do { \
    CUresult r = (call); \
    if (r != CUDA_SUCCESS) { \
        const char *msg; \
        cuGetErrorString(r, &msg); \
        fprintf(stderr, "CUDA error: %s at %s:%d\n", msg, __FILE__, __LINE__); \
        exit(1); \
    } \
} while (0)

int main(void) {
    /* Initialize CUDA driver API */
    CHECK_CUDA(cuInit(0));

    /* Initialize sm121-kernels */
    SparkCtx *ctx = NULL;
    CHECK_SPARK(spark_init(0, &ctx));
    printf("sm121-kernels initialized on device 0\n");

    /* Allocate BF16 GEMM buffers: C[128,128] = A[128,128] x B[128,128] */
    unsigned int m = 128, n = 128, k = 128;
    size_t mat_bytes = (size_t)m * k * 2; /* bf16 = 2 bytes */

    CUdeviceptr a_dev, b_dev, c_dev;
    CHECK_CUDA(cuMemAlloc(&a_dev, mat_bytes));
    CHECK_CUDA(cuMemAlloc(&b_dev, mat_bytes));
    CHECK_CUDA(cuMemAlloc(&c_dev, mat_bytes));
    CHECK_CUDA(cuMemsetD8(a_dev, 0, mat_bytes));
    CHECK_CUDA(cuMemsetD8(b_dev, 0, mat_bytes));

    /* Launch BF16 GEMM */
    SparkGemmParams gemm_params = {
        .a = (const uint8_t *)a_dev,
        .b = (const uint8_t *)b_dev,
        .c = (uint8_t *)c_dev,
        .m = m,
        .n = n,
        .k = k,
        .dtype = SPARK_DTYPE_BF16,
    };
    CHECK_SPARK(spark_gemm(ctx, &gemm_params));
    printf("BF16 GEMM %ux%ux%u completed\n", m, n, k);

    /* ============================================================ */
    /* Flash Attention: BF16, B=1, H=4, Sq=Skv=128, D=128          */
    /* ============================================================ */
    unsigned int batch = 1, num_heads = 4, seq_q = 128, seq_kv = 128, head_dim = 128;
    float scale = 1.0f / sqrtf((float)head_dim);

    size_t qo_elems = (size_t)batch * num_heads * seq_q * head_dim;
    size_t kv_elems = (size_t)batch * num_heads * seq_kv * head_dim;
    size_t qo_bytes = qo_elems * 2; /* bf16 */
    size_t kv_bytes = kv_elems * 2;

    CUdeviceptr q_dev, k_dev, v_dev, o_dev;
    CHECK_CUDA(cuMemAlloc(&q_dev, qo_bytes));
    CHECK_CUDA(cuMemAlloc(&k_dev, kv_bytes));
    CHECK_CUDA(cuMemAlloc(&v_dev, kv_bytes));
    CHECK_CUDA(cuMemAlloc(&o_dev, qo_bytes));
    CHECK_CUDA(cuMemsetD8(q_dev, 0, qo_bytes));
    CHECK_CUDA(cuMemsetD8(k_dev, 0, kv_bytes));
    CHECK_CUDA(cuMemsetD8(v_dev, 0, kv_bytes));

    SparkFlashAttnParams attn_params = {
        .q = (const uint8_t *)q_dev,
        .k = (const uint8_t *)k_dev,
        .v = (const uint8_t *)v_dev,
        .o = (uint8_t *)o_dev,
        .batch = batch,
        .num_heads = num_heads,
        .seq_q = seq_q,
        .seq_kv = seq_kv,
        .head_dim = head_dim,
        .scale = scale,
        .causal = 0,
        .dtype = SPARK_DTYPE_BF16,
    };
    CHECK_SPARK(spark_flash_attention(ctx, &attn_params));
    printf("BF16 Flash Attention B=%u H=%u Sq=%u Skv=%u D=%u completed\n",
           batch, num_heads, seq_q, seq_kv, head_dim);

    /* Causal attention */
    attn_params.causal = 1;
    CHECK_SPARK(spark_flash_attention(ctx, &attn_params));
    printf("BF16 Flash Attention (causal) completed\n");

    /* FP8 attention */
    CUdeviceptr q_fp8, k_fp8, v_fp8;
    size_t qo_fp8_bytes = qo_elems; /* fp8 = 1 byte */
    size_t kv_fp8_bytes = kv_elems;
    CHECK_CUDA(cuMemAlloc(&q_fp8, qo_fp8_bytes));
    CHECK_CUDA(cuMemAlloc(&k_fp8, kv_fp8_bytes));
    CHECK_CUDA(cuMemAlloc(&v_fp8, kv_fp8_bytes));
    CHECK_CUDA(cuMemsetD8(q_fp8, 0, qo_fp8_bytes));
    CHECK_CUDA(cuMemsetD8(k_fp8, 0, kv_fp8_bytes));
    CHECK_CUDA(cuMemsetD8(v_fp8, 0, kv_fp8_bytes));

    SparkFlashAttnParams fp8_params = {
        .q = (const uint8_t *)q_fp8,
        .k = (const uint8_t *)k_fp8,
        .v = (const uint8_t *)v_fp8,
        .o = (uint8_t *)o_dev,  /* output is still bf16 */
        .batch = batch,
        .num_heads = num_heads,
        .seq_q = seq_q,
        .seq_kv = seq_kv,
        .head_dim = head_dim,
        .scale = scale,
        .causal = 0,
        .dtype = SPARK_DTYPE_FP8E4M3,
    };
    CHECK_SPARK(spark_flash_attention(ctx, &fp8_params));
    printf("FP8 Flash Attention completed\n");

    /* ============================================================ */
    /* RMSNorm + SiLU + RoPE pipeline                               */
    /* ============================================================ */
    unsigned int hidden_dim = 4096;
    unsigned int num_rows = 128;
    size_t norm_bytes = (size_t)num_rows * hidden_dim * 2;

    CUdeviceptr x_dev, w_dev, norm_out;
    CHECK_CUDA(cuMemAlloc(&x_dev, norm_bytes));
    CHECK_CUDA(cuMemAlloc(&w_dev, (size_t)hidden_dim * 2));
    CHECK_CUDA(cuMemAlloc(&norm_out, norm_bytes));
    CHECK_CUDA(cuMemsetD8(x_dev, 0, norm_bytes));
    CHECK_CUDA(cuMemsetD8(w_dev, 0, (size_t)hidden_dim * 2));

    SparkRmsNormParams norm_params = {
        .x = (const uint8_t *)x_dev,
        .weight = (const uint8_t *)w_dev,
        .out = (uint8_t *)norm_out,
        .hidden_dim = hidden_dim,
        .num_rows = num_rows,
        .eps = 1e-5f,
    };
    CHECK_SPARK(spark_rmsnorm(ctx, &norm_params));
    printf("RMSNorm %ux%u completed\n", num_rows, hidden_dim);

    /* Clean up */
    CHECK_CUDA(cuMemFree(a_dev));
    CHECK_CUDA(cuMemFree(b_dev));
    CHECK_CUDA(cuMemFree(c_dev));
    CHECK_CUDA(cuMemFree(q_dev));
    CHECK_CUDA(cuMemFree(k_dev));
    CHECK_CUDA(cuMemFree(v_dev));
    CHECK_CUDA(cuMemFree(o_dev));
    CHECK_CUDA(cuMemFree(q_fp8));
    CHECK_CUDA(cuMemFree(k_fp8));
    CHECK_CUDA(cuMemFree(v_fp8));
    CHECK_CUDA(cuMemFree(x_dev));
    CHECK_CUDA(cuMemFree(w_dev));
    CHECK_CUDA(cuMemFree(norm_out));

    CHECK_SPARK(spark_destroy(ctx));
    printf("\nsm121-kernels C API demo complete.\n");
    printf("All kernels launched successfully — zero Python, zero CUDA toolkit.\n");

    return 0;
}
