use std::collections::HashMap;
use std::sync::Arc;

use cudarc::driver::{CudaContext, CudaFunction};
use cudarc::nvrtc::Ptx;

use crate::error::{Result, SparkError};

// Generated by build.rs: maps kernel names to embedded cubin bytes.
#[allow(missing_docs)]
mod embedded {
    use super::*;
    include!(concat!(env!("OUT_DIR"), "/embedded_kernels.rs"));
}
use embedded::{KERNEL_PTX_REGISTRY, KERNEL_REGISTRY};

/// Global function cache keyed by (device ordinal, "kernel::entry").
/// Avoids re-loading cubins on every kernel dispatch.
///
/// Uses double-checked locking: read lock for fast cache hits, write lock
/// with re-check for cold loads. Concurrent cold loads to the same key
/// are deduplicated by the re-check under write lock. parking_lot::RwLock
/// is used over std::sync::RwLock for performance (no poisoning, faster
/// uncontended path).
static FUNCTION_CACHE: parking_lot::RwLock<Option<HashMap<(usize, String), CudaFunction>>> =
    parking_lot::RwLock::new(None);

fn ensure_cache() {
    let read = FUNCTION_CACHE.read();
    if read.is_some() {
        return;
    }
    drop(read);
    let mut write = FUNCTION_CACHE.write();
    if write.is_none() {
        *write = Some(HashMap::new());
    }
}

/// Load a compiled kernel function from the embedded cubin registry.
///
/// `kernel_name` matches the PTX file stem (e.g. "vector_add").
/// `entry_point` is the `.entry` function name inside that cubin.
///
/// Results are cached per (device, kernel, entry) triple.
/// The cubin is written to a temp file and loaded via `Ptx::from_file`,
/// which internally calls `cuModuleLoad` — this accepts cubin ELF binaries.
pub fn load_kernel(
    ctx: &Arc<CudaContext>,
    kernel_name: &'static str,
    entry_point: &str,
) -> Result<CudaFunction> {
    ensure_cache();

    let cache_key = (ctx.ordinal(), format!("{kernel_name}::{entry_point}"));

    // Fast path: check cache under read lock.
    {
        let cache = FUNCTION_CACHE.read();
        if let Some(map) = cache.as_ref() {
            if let Some(func) = map.get(&cache_key) {
                return Ok(func.clone());
            }
        }
    }

    // Slow path: acquire write lock first to prevent duplicate loads.
    let mut cache = FUNCTION_CACHE.write();
    let map = cache.as_mut().unwrap();

    // Double-check under write lock (another thread may have loaded it).
    if let Some(func) = map.get(&cache_key) {
        return Ok(func.clone());
    }

    // Load cubin from registry, write to temp file, load module.
    let cubin_bytes = KERNEL_REGISTRY
        .get(kernel_name)
        .ok_or_else(|| SparkError::KernelNotFound(kernel_name.to_string()))?;

    // cudarc's Ptx::Image is pub(crate), so we write the cubin to a temp file
    // and use Ptx::from_file. cuModuleLoad accepts cubin ELF via file path.
    let tmp_path =
        std::env::temp_dir().join(format!("spark_{kernel_name}_{}.cubin", std::process::id()));
    std::fs::write(&tmp_path, cubin_bytes)
        .map_err(|e| SparkError::LaunchFailed(format!("failed to write cubin temp file: {e}")))?;

    // Fast path: load the sm_121a cubin directly (no JIT). On any other SM12x arch the
    // driver rejects the cubin; fall back to JIT-compiling the embedded preprocessed PTX.
    let module = match ctx.load_module(Ptx::from_file(&tmp_path)) {
        Ok(m) => {
            let _ = std::fs::remove_file(&tmp_path);
            m
        }
        Err(cubin_err) => {
            let _ = std::fs::remove_file(&tmp_path);
            let ptx_bytes = KERNEL_PTX_REGISTRY.get(kernel_name).ok_or(cubin_err)?;
            let ptx_path = std::env::temp_dir()
                .join(format!("spark_{kernel_name}_{}.ptx", std::process::id()));
            std::fs::write(&ptx_path, ptx_bytes).map_err(|e| {
                SparkError::LaunchFailed(format!("failed to write ptx temp file: {e}"))
            })?;
            let m = ctx.load_module(Ptx::from_file(&ptx_path))?;
            let _ = std::fs::remove_file(&ptx_path);
            m
        }
    };

    let func = module.load_function(entry_point)?;
    map.insert(cache_key, func.clone());

    Ok(func)
}

/// Per-(device, kernel, entry) cache for `load_kernel_raw`.
///
/// Before this cache, every call to `load_kernel_raw` did:
///   write cubin to /tmp → cuModuleLoad → cuModuleGetFunction → remove temp
/// and the resulting CUmodule was NEVER freed (only `CUfunction` returned;
/// the module handle leaked). Each call leaked ~1-2 MiB of GPU module memory.
///
/// Under HTTP load this leaked at ~100 modules/wave (24 GDN + 8 FA layers ×
/// multiple TMA/non-TMA kernels × 25 ticks/wave), which:
///   - Caused a ~70 MiB/wave memory drift under sustained-load soak testing.
///   - Exhausted CUDA's module pool, triggering CUDA_ERROR_FILE_NOT_FOUND /
///     INVALID_IMAGE on subsequent cuModuleLoad calls (Sessions 73-77).
///
/// The fix caches the CUfunction handle on first load and returns the cached
/// handle thereafter. CUfunction is `Copy` (raw pointer); safe to clone.
/// CUfunction is a raw pointer (`*mut CUfunc_st`); the underlying object is
/// owned by the CUDA driver for the process lifetime and is safe to share
/// across threads (loads are atomic from caller's POV; kernel launches with
/// a CUfunction are inherently multi-threaded in CUDA's design).
#[derive(Copy, Clone)]
struct SendCUfunction(cudarc::driver::sys::CUfunction);
unsafe impl Send for SendCUfunction {}
unsafe impl Sync for SendCUfunction {}

static FUNCTION_CACHE_RAW: parking_lot::RwLock<
    Option<HashMap<(usize, u64, String), SendCUfunction>>,
> = parking_lot::RwLock::new(None);

/// Context-generation registry. A CUcontext address can be REUSED by the
/// driver after the previous context at that address is destroyed, so the
/// address alone cannot distinguish "same context" from "new context at the
/// same address". `device::init_device` stamps every context it creates with
/// a fresh monotonically-increasing generation; the raw-kernel cache keys on
/// it, so entries from a destroyed context are simply never consulted again.
/// Contexts created outside `init_device` map to generation 0 and are covered
/// by the liveness probe in `load_kernel_raw` instead.
static CONTEXT_GENERATIONS: parking_lot::Mutex<Option<HashMap<usize, u64>>> =
    parking_lot::Mutex::new(None);
static NEXT_GENERATION: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);

/// Stamp `ctx` with a fresh generation (called by `device::init_device`).
pub(crate) fn register_context(ctx: &Arc<CudaContext>) {
    let generation = NEXT_GENERATION.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let mut reg = CONTEXT_GENERATIONS.lock();
    reg.get_or_insert_with(HashMap::new)
        .insert(ctx.cu_ctx() as usize, generation);
}

fn context_generation(ctx: &Arc<CudaContext>) -> u64 {
    let reg = CONTEXT_GENERATIONS.lock();
    reg.as_ref()
        .and_then(|m| m.get(&(ctx.cu_ctx() as usize)).copied())
        .unwrap_or(0)
}

fn ensure_cache_raw() {
    let read = FUNCTION_CACHE_RAW.read();
    if read.is_some() {
        return;
    }
    drop(read);
    let mut write = FUNCTION_CACHE_RAW.write();
    if write.is_none() {
        *write = Some(HashMap::new());
    }
}

/// Load a kernel and return the raw CUfunction handle for use with cuLaunchKernel.
///
/// This is needed for kernels with non-standard parameter types (e.g., TMA
/// tensor map descriptors) that cudarc's PushKernelArg doesn't support.
///
/// Cached per (device ordinal, kernel name, entry point) — the cold load
/// path runs once per kernel per device and re-uses thereafter.
pub fn load_kernel_raw(
    ctx: &Arc<CudaContext>,
    kernel_name: &'static str,
    entry_point: &str,
) -> Result<cudarc::driver::sys::CUfunction> {
    ensure_cache_raw();
    // The cached value is a BARE CUfunction pointer: unlike cudarc's
    // `CudaFunction` (which Arc-holds its context alive), it dangles if the
    // context it was loaded in is destroyed — and a new context on the same
    // device can even reuse the freed address, so no address-based key can
    // rule out a stale handle. The key therefore includes the context
    // GENERATION stamped by `device::init_device` (a recreated context gets a
    // new generation, so dead entries are never consulted). For contexts not
    // created through `init_device` (generation 0), the hit path additionally
    // VERIFIES the handle with a cheap attribute query and reloads if dead.
    let generation = context_generation(ctx);
    let cache_key = (
        ctx.ordinal(),
        generation,
        format!("{kernel_name}::{entry_point}"),
    );
    let func_is_live = |f: cudarc::driver::sys::CUfunction| -> bool {
        use cudarc::driver::sys::*;
        let mut v: i32 = 0;
        unsafe {
            cuFuncGetAttribute(
                &mut v,
                CUfunction_attribute::CU_FUNC_ATTRIBUTE_MAX_THREADS_PER_BLOCK,
                f,
            ) == CUresult::CUDA_SUCCESS
        }
    };
    // Fast path: cache hit under read lock.
    {
        let cache = FUNCTION_CACHE_RAW.read();
        if let Some(map) = cache.as_ref() {
            if let Some(func) = map.get(&cache_key) {
                if generation != 0 || func_is_live(func.0) {
                    return Ok(func.0);
                }
                // generation-0 stale handle — fall through to reload
            }
        }
    }
    // Slow path: write lock + double-check + cold load.
    let mut cache = FUNCTION_CACHE_RAW.write();
    let map = cache.as_mut().unwrap();
    if let Some(func) = map.get(&cache_key) {
        if generation != 0 || func_is_live(func.0) {
            return Ok(func.0);
        }
        map.remove(&cache_key);
    }

    use cudarc::driver::sys::*;

    let cubin_bytes = KERNEL_REGISTRY
        .get(kernel_name)
        .ok_or_else(|| SparkError::KernelNotFound(kernel_name.to_string()))?;

    let tmp_path = std::env::temp_dir().join(format!(
        "spark_raw_{kernel_name}_{}.cubin",
        std::process::id()
    ));
    std::fs::write(&tmp_path, cubin_bytes)
        .map_err(|e| SparkError::LaunchFailed(format!("write cubin: {e}")))?;

    let path_cstr = std::ffi::CString::new(tmp_path.to_str().unwrap())
        .map_err(|e| SparkError::LaunchFailed(format!("cstring: {e}")))?;

    let mut cu_module: CUmodule = std::ptr::null_mut();
    let load_result = unsafe { cuModuleLoad(&mut cu_module, path_cstr.as_ptr()) };
    let _ = std::fs::remove_file(&tmp_path);

    if load_result != CUresult::CUDA_SUCCESS {
        // Forward-compat: the sm_121a cubin is rejected on other SM12x archs; fall back
        // to JIT-compiling the embedded preprocessed PTX (cuModuleLoad JITs PTX).
        let ptx_bytes = KERNEL_PTX_REGISTRY.get(kernel_name).ok_or_else(|| {
            SparkError::LaunchFailed(format!("cuModuleLoad failed: {:?}", load_result))
        })?;
        let ptx_path = std::env::temp_dir().join(format!(
            "spark_raw_{kernel_name}_{}.ptx",
            std::process::id()
        ));
        std::fs::write(&ptx_path, ptx_bytes)
            .map_err(|e| SparkError::LaunchFailed(format!("write ptx: {e}")))?;
        let ptx_cstr = std::ffi::CString::new(ptx_path.to_str().unwrap())
            .map_err(|e| SparkError::LaunchFailed(format!("cstring: {e}")))?;
        let ptx_load = unsafe { cuModuleLoad(&mut cu_module, ptx_cstr.as_ptr()) };
        let _ = std::fs::remove_file(&ptx_path);
        if ptx_load != CUresult::CUDA_SUCCESS {
            return Err(SparkError::LaunchFailed(format!(
                "cuModuleLoad failed for both cubin ({:?}) and PTX JIT ({:?})",
                load_result, ptx_load
            )));
        }
    }

    let entry_cstr = std::ffi::CString::new(entry_point)
        .map_err(|e| SparkError::LaunchFailed(format!("cstring: {e}")))?;

    let mut cu_func: CUfunction = std::ptr::null_mut();
    let get_result = unsafe { cuModuleGetFunction(&mut cu_func, cu_module, entry_cstr.as_ptr()) };

    if get_result != CUresult::CUDA_SUCCESS {
        return Err(SparkError::LaunchFailed(format!(
            "cuModuleGetFunction failed: {:?}",
            get_result
        )));
    }

    // Cache the function handle. Note: the CUmodule handle is intentionally
    // kept alive for the process lifetime (we don't store it but cuModuleLoad
    // ensures the module persists until cuModuleUnload or process exit).
    map.insert(cache_key, SendCUfunction(cu_func));
    Ok(cu_func)
}
